#!/usr/bin/bash

swww_fork=~/.config/hypr/scripts/tools/swww

isRunning=$(pidof swww)

if [[ $isRunning -eq "" ]]; then
	$swww_fork init
else
	echo "swww is already running"
fi
$swww_fork img $1 --transition-type grow --transition-pos 0.9,0.1 --transition-duration 3 
